from database.model.mission import MISSION_MODEL_TYPE

from rostek_utils.utils.pattern import Define_Class

class MISSION_TYPE_MAPPING(Define_Class):
    MANUAL_INPUT = [
        MISSION_MODEL_TYPE.MANUAL_PALLET_1,
        MISSION_MODEL_TYPE.MANUAL_PALLET_2,
        MISSION_MODEL_TYPE.MANUAL_PALLET_3,
        MISSION_MODEL_TYPE.MANUAL_PALLET_4,
        MISSION_MODEL_TYPE.MANUAL_PALLET_5,
        MISSION_MODEL_TYPE.MANUAL_CARTON_1,
        MISSION_MODEL_TYPE.MANUAL_CARTON_2,
        MISSION_MODEL_TYPE.MANUAL_CARTON_3,
        MISSION_MODEL_TYPE.MANUAL_CARTON_4,
        MISSION_MODEL_TYPE.MANUAL_CARTON_5
    ]
    MANUAL_OUTPUT = [
        MISSION_MODEL_TYPE.MANUAL_PRODUCT_1,
        MISSION_MODEL_TYPE.MANUAL_PRODUCT_2,
        MISSION_MODEL_TYPE.MANUAL_PRODUCT_3,
        MISSION_MODEL_TYPE.MANUAL_PRODUCT_4,
        MISSION_MODEL_TYPE.MANUAL_PRODUCT_5
    ]
    AUTO_INPUT = [MISSION_MODEL_TYPE.AUTO_PALLET]
    AUTO_OUTPUT = [
        MISSION_MODEL_TYPE.AUTO_PRODUCT_1,
        MISSION_MODEL_TYPE.AUTO_PRODUCT_2
    ]
    PWM_OUTPUT = [MISSION_MODEL_TYPE.PWM_PRODUCT]

DEVICE_CONNECTION_TIMEOUT = 15 # in second